apiVersion: v1
kind: Service
metadata:
  #name: {{ include "productpage-service.fullname" . }}
  name: {{ .Values.service.name }}
  labels:
    {{- include "productpage-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "productpage-service.selectorLabels" . | nindent 4 }}
